version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    networks:
      - backend-mongo
    volumes:
      - dbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  backend:
    depends_on:
      - mongodb
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    networks:
      - backend-mongo
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/home/node/backend
      - node_modules:/home/node/backend/node_modules

networks:
  backend-mongo:
    driver: bridge
volumes:
  dbdata:
  node_modules:
